config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users, :groups
  get '/groups/mygroup/:id', to: 'groups#mygroup', as: 'mygroup'
  post '/groups/join_group/:id', to: 'groups#join_group', as: 'join'
end
  

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id               :integer          not null, primary key
#  name             :string
#  description      :text
#  location         :string
#  owner            :string
#  background_image :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Group < ApplicationRecord

	has_many :posts
	has_many :comments, through: :posts
	has_and_belongs_to_many :users, optional: true

	def self.search(search)
 		where("name LIKE ?", "%#{search}%") 
  	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_group, only: [:show, :edit, :update, :destroy]

	def index
		@groups = Group.all.order('created_at ASC')
		if params[:search]
			@groups = Group.search(params[:search]).order("created_at ASC")
		else
			@groups = Group.all.order('created_at ASC')
		end
	end

	def show
		@groups = Group.all
		@group = Group.find(params[:id])
	end


	def index
		@groups = Group.all.order('created_at ASC')
		if params[:search]
			@groups = Group.search(params[:search]).order("created_at ASC")
		else
			@groups = Group.all.order('created_at ASC')
		end
	end

	def mygroup
		@user = User.find (params[:id])
	end


	def new
		@group = Group.new
	end

	def create
		@group = Group.new(group_params)

		respond_to do |format|
			if @group.save
				format.html { redirect_to @group, notice: 'Group was successfully created.' }
				format.json { render :show, status: :created, location: @group }
			else
				format.html { render :new }
				format.json { render json: @group.errors, status: :unprocessable_entity }
			end
		end
	end


	def edit
		@group = Group.find(params[:id])
	end


	def update
		respond_to do |format|
			if @group.update(group_params)
				format.html { redirect_to @group, notice: 'Group was successfully updated.' }
				format.json { render :show, status: :ok, location: @group }
			else
				format.html { render :edit }
				format.json { render json: @group.errors, status: :unprocessable_entity }
			end
		end
	end

	def join_group
		@group = Group.find(params[:id])
		current_user.groups << @group
		redirect_to :back, notice: 'Joined!'
	end


	private
# Use callbacks to share common setup or constraints between actions.
def set_group
	@group = Group.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def group_params
	params.require(:group).permit(:name, :description, :location, :owner, :background_image)
end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
  <div class="container">
    <h1></h1>
    <hr>
    <div class="row">
      <!-- left column -->
      <div class="col-md-3">
        <div class="text-center">
          <img src="https://placehold.it/200x100" class="" alt="avatar">
          <h6>Upload a different photo...</h6>

          <input type="file" class="form-control">
        </div>
      </div>

      <!-- edit form column -->
      <div class="col-md-9 personal-info">
        <%= bootstrap_form_for(@group) do |f| %>
        <% if @group.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
            <% group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <h2>Group Info</h2>
        <div class="col-xs-8 col-xs-offset-2">
          <div class="field">
            <%= f.text_field :name %>
          </div>

          <div class="field">
            <%= f.text_field :description %>
          </div>

          <div class="field">
            <%= f.text_field :location %>
          </div>

          <div class="field">
            <%= f.text_field :owner, placeholder: "#{current_user.username}"  %>
          </div>

          <div class="field">
            <%= f.text_field :background_image %>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <hr>
  <% end %>

app/views/groups/edit.html.erb
<% provide(:title, "Edit #{@group.name}") %>
<%= render 'form', group: @group %>

app/views/groups/index.html.erb
 <% provide(:title, "Explore Groups") %>
  <div class="container">
    <div class="fb-profile">
      <img align="left" class="fb-image-lg" src="http://placehold.it/2050x350" alt="Profile image example"/>
      <img align="left" class="fb-image-profile thumbnail" src="http://placehold.it/200x200" alt="Profile image example"/>
    </div>
  </div> 


  <div class= "container formpadding">
    <div class= "row">

      <!-- Left side -->
      <div class= "container col-xs-3">
        <div class = "row">
          <div class="panel panel-default col-xs-12">
            <div class="panel-body">
              <div class="row">
                <div class="panel panel-default">
                  <!-- Default panel contents -->
                  <!-- List group -->
                  <ul class="list-group">
                    <li class="list-group-item"><%= link_to 'Home', root_path %></li>
                    <li class="list-group-item"><%= link_to 'My Profile', user_path(current_user) %></li>
                    <li class="list-group-item"><%= link_to 'My Groups', mygroup_path(current_user) %></li>
                    <li class="list-group-item"><%= link_to 'Create Group', new_group_path%></li>
                    <li class="list-group-item"><%= link_to 'Explore Groups', groups_path %></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


      <!-- Right side -->
      <div class= "container col-xs-9">
        <div class = "row"> 
          <div class="panel panel-default col-xs-10 col-xs-offset-1">
            <h2 class=""> Explore Groups  </h2>
            <span>
              <%= form_tag(groups_path, :method => "get", id: "search-form") do %>
              <%= text_field_tag :search, params[:search], placeholder: "Search Groups" %>
              <%= submit_tag "Search" %>
              <% end %>
            </span>
            <hr>
            <div class="panel-body">

              <!-- activity blocks go here -->
              <% @groups.each do |group| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title"> <%= link_to "#{group.name}", group_path(group) %> 
                      <span class ="small-muted">
                        <i>
                          Owner: <%= group.owner %> 
                        </i> 
                      </span>
                    </h3>
                  </div>
                  <div class="panel-body">
                    <%= group.description %>
                  </div>
                </div>

                <br>
                <% end %>

                <!-- activity blocks end here -->

              </div>
            </div>
          </div> 
        </div>

app/views/groups/mygroup.html.erb
  <% provide(:title, "My Groups") %>
  <div class="container">
    <div class="fb-profile">
      <img align="left" class="fb-image-lg" src="http://placehold.it/2050x350" alt="Profile image example"/>
      <img align="left" class="fb-image-profile thumbnail" src="http://placehold.it/200x200" alt="Profile image example"/>
    </div>
  </div> 
  <div class= "container formpadding">
    <div class= "row">

      <!-- Left side -->
      <div class= "container col-xs-3">
        <div class = "row">
          <div class="panel panel-default col-xs-12">
            <div class="panel-body">
              <div class="row">
                <div class="panel panel-default">
                  <!-- Default panel contents -->
                  <!-- List group -->
                  <ul class="list-group">
                    <li class="list-group-item"><%= link_to 'Home', root_path %></li>
                    <li class="list-group-item"><%= link_to 'My Profile', user_path(current_user) %></li>
                    <li class="list-group-item"><%= link_to 'My Groups', mygroup_path(current_user) %></li>
                    <li class="list-group-item"><%= link_to 'Create Group', new_group_path%></li>
                    <li class="list-group-item"><%= link_to 'Explore Groups', groups_path %></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>


      <!-- Right side -->
      <div class= "container col-xs-9">
        <div class = "row"> 
          <div class="panel panel-default col-xs-10 col-xs-offset-1">
            <h2 class=""> My Groups </h2>
            <hr>
            <div class="panel-body">

              <!-- activity blocks go here -->
              <% @user.groups.each do |group| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title"> <%= link_to "#{group.name}", group_path(group) %> 
                    <span class ="small-muted">
                      <i>
                        Owner: <%= group.owner %> 
                      </i> 
                    </span>
                  </h3>
                </div>
                <div class="panel-body">
                  <%= group.description %>
                </div>
              </div>

              <br>
              <% end %>

              <!-- activity blocks end here -->

            </div>
          </div>
        </div> 
      </div>
     </div> 
    </div>

app/views/groups/new.html.erb
<% provide(:title, "Create Group") %>
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<% provide(:title, "#{@group.name}") %>
  <div class="container">
    <div class="fb-profile">
      <img align="left" class="fb-image-lg" src="http://placehold.it/2050x350" alt="Profile image example"/>
      <img align="left" class="fb-image-profile thumbnail" src="http://placehold.it/200x200" alt="Profile image example"/>
    </div>
  </div> 
  <div class= "container formpadding">
    <div class= "row">
      <!-- Left side -->
      <div class= "container col-xs-3">
        <div class = "row">
          <div class="panel panel-default col-xs-12">
            <div class="panel-body">
              <div class="row">
                <div class="panel panel-default">
                  <!-- Default panel contents -->
                  <!-- List group -->
                  <ul class="list-group">
                    <li class="list-group-item"><%= link_to 'Home', root_path %></li>
                    <li class="list-group-item"><%= link_to 'My Profile', user_path(current_user) %></li>
                    <li class="list-group-item"><%= link_to 'My Groups', mygroup_path(current_user) %></li>
                    <li class="list-group-item"><%= link_to 'Create Group', new_group_path%></li>
                    <li class="list-group-item"><%= link_to 'Explore Groups', groups_path %></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class ="row">
          <form>
            <div class="form-group">
              <label for="comment">Comment:</label>
              <textarea class="form-control" rows="5" id="comment"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </div>
      </div>


      <!-- Right side -->
      <div class= "container col-xs-9">
        <div class = "row"> 
          <div class="panel panel-default col-xs-10 col-xs-offset-1">
            <h3 class=""> <%= @group.name%> 
              <% if @group.owner == current_user.username %>
              <span class ="medium-muted">  
                  <%= link_to "Edit", edit_group_path %> 
              </span>
              <%end%>
              <span class= "medium-muted">
              <%= button_to "Join Group", action: "join_group" %>
              </span>
            </h3>
            <hr>
            <div class="panel-body">
              <!-- activity blocks go here -->
              <% @group.posts.each do |post| %>
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title"> <b> <%= post.title %> </b> 
                    <span class ="small-muted"> 
                      <i> posted by 
                        <%= link_to "#{post.user.username}", user_path(post.user) %> @ <%= post.created_at %> 
                      </i>
                    </span>
                  </h3>
                </div>
                <div class="panel-body">
                  <%= post.description %>
                </div>
              </div>
              <br>
              <% end %>
              <!-- activity blocks end here -->
            </div>
          </div>
        </div> 
      </div>
    </div>
  </div>