config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users, :groups
  get '/groups/mygroup/:id', to: 'groups#mygroup', as: 'mygroup'
  post '/groups/join_group/:id', to: 'groups#join_group', as: 'join'
end
  

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string
#  email                  :string
#  first_name             :string
#  last_name              :string
#  street                 :string
#  city                   :string
#  state                  :string
#  zip_code               :integer
#  about_me               :text
#  profile_image          :string
#  background_image       :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  password_confirmation  :string
#  encrypted_password     :string
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  sign_in_count          :integer
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  reset_password_token   :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
# Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable and :omniauthable
has_many :posts
has_many :comments, through: :posts
has_and_belongs_to_many :groups, optional: true
validates :first_name, length: { maximum: 10}
validates :last_name, length: { maximum: 10}
validates :username, length: { maximum: 10}
validates :zip_code, length: { maximum:9}
validates :email, allow_blank: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
validates :street, length: { maximum: 20}
validates :city, length: { maximum: 20}
validates :state, length: { maximum: 20}
validates :about_me, length: { maximum: 100}



devise :database_authenticatable, :registerable,
:recoverable, :rememberable, :trackable, :validatable



end         

#  id               :integer          not null, primary key
#  username         :string
#  password         :string
#  email            :string
#  first_name       :string
#  last_name        :string
#  street           :string
#  city             :string
#  state            :string
#  zip_code         :integer
#  about_me         :text
#  profile_image    :string
#  background_image :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
# GET /users
# GET /users.json
def index
  @users = User.all
end

# GET /users/1
# GET /users/1.json
def show
  @user = User.find(params[:id])
 # unless @user == current_user
#  redirect_to :back, :alert => "Access denied."
  end

# GET /users/new
def new
  @user = User.new
end

# GET /users/1/edit
def edit
end

# POST /users
# POST /users.json
def create
  @user = User.new(user_params)

  respond_to do |format|
    if @user.save
      format.html { redirect_to @user, notice: 'User was successfully created.' }
      format.json { render :show, status: :created, location: @user }
    else
      format.html { render :new }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

# PATCH/PUT /users/1
# PATCH/PUT /users/1.json
def update
  respond_to do |format|
    if @user.update(user_params)
      format.html { redirect_to @user, notice: 'User was successfully updated.' }
      format.json { render :show, status: :ok, location: @user }
    else
      format.html { render :edit }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

# DELETE /users/1
# DELETE /users/1.json
def destroy
  @user.destroy
  respond_to do |format|
    format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    format.json { head :no_content }
  end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_user
  @user = User.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def user_params
  params.require(:user).permit(:user_name, :email, :first_name, :last_name, :street, :city, :state, :zip_code, :about_me, :profile_image, :background_image )
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <div class="container">
    <h1>Edit Profile</h1>
    <hr>
    <div class="row">
      <!-- left column -->
      <div class="col-md-3">
        <div class="text-center">
          <img src="https://placehold.it/200x100" class="" alt="avatar">
          <h6>Upload a different photo...</h6>

          <input type="file" class="form-control">
        </div>
      </div>

      <!-- edit form column -->
      <div class="col-md-9">
        <%= bootstrap_form_for(@user) do |f| %>
        <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being updated:</h2>

          <ul>
            <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <h2>Personal Info</h2>
        <div class="col-xs-8 col-xs-offset-2">
          <div class="field">
            <%= f.text_field :first_name %>
          </div>

          <div class="field">
            <%= f.text_field :last_name %>
          </div>

          <div class="field">
            <%= f.text_field :street  %>
          </div>

          <div class="field">
            <%= f.text_field :city %>
          </div>

          <div class="field">
            <%= f.text_field :state %>
          </div>

          <div class="field">
            <%= f.text_field :zip_code %>
          </div>

          <div class="field">
            <%= f.text_field :about_me%>
          </div>

          <div class="field">
            <%= f.text_field :profile_image %>
          </div>

          <div class="field">
            <%= f.text_field :background_image %>
          </div>

          <div class="actions">
            <%= f.submit %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <br>
  <br>
  <% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<%= render 'form', user:@user %>

app/views/users/show.html.erb
<% provide(:title, "My Profile") %>
<div class="container">
  <div class="fb-profile">
    <img align="left" class="fb-image-lg" src="http://placehold.it/2050x350" alt="Profile image example"/>
    <img align="left" class="fb-image-profile thumbnail" src="http://placehold.it/550x550" alt="Profile image example"/>
    <div class="fb-profile-text">
      <h1><%= @user.first_name + " " + @user.last_name %> 
        <span class="text-muted medium-muted"><%=@user.city+","+@user.state %> <%=link_to 'Edit', edit_user_path(@user)%> 
        </span>
      </h1>
    </div>
  </div>
</div> <!-- /container -->  
<br>
<br>
<div class= "container col-xs-6 col-xs-offset-3">
  <div class="row">
    <div class="panel panel-default ">
      <div class="panel-heading">
        <h1 class="panel-title">Bio</h1>
      </div>
      <div class="panel-body">
        <%= @user.about_me %>
      </div>
    </div>
  </div>
</div>

<!-- Right side -->
<div class= "container col-xs-6 col-xs-offset-3">
  <div class = "row"> 
    <div class="panel panel-default col-xs-10 col-xs-offset-1">
      <h2 class=""> Recent Activity </h2>
      <hr>
      <div class="panel-body">
        <!-- activity blocks go here -->
        <% @user.posts.each do |post| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"> <b> <%= post.title %> </b> <span class ="small-muted"> <i> posted in 
              <%= link_to "#{post.group.name}", group_path(post.group) %> @ <%= post.created_at %> </i></span></h3>
            </div>
            <div class="panel-body">
              <%= post.description %>
            </div>
          </div>

          <br>
          <% end %>
          <!-- activity blocks end here --> 
        </div>
      </div>
    </div> 
  </div>